# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stefano Ricciardi
name: Stefano Ricciardi
description: Stefano Ricciardi on Software Development
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stefanoric
github_username:  stefanoric

# Site owner
author:
  name                   : "Stefano Ricciardi"
  url                    : "https://stefanoricciardi.com/about/"
  bio                    : "Just another software developer"
  picture                : "/assets/bw_avatar_128x128.jpg"
  twitter                : "stefanoric"
  github                 : "stefanoric"

comments:
  provider: disqus
  disqus:
    shortname: stefanoricciardicom

analytics:
  provider: google
  google:
    tracking_id: "UA-15612899-1"

# Build settings
markdown: kramdown
#theme: minima
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]

permalink: /:year/:month/:day/:title/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

