# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
locale: "en"
title: Stefano Ricciardi
name: Stefano Ricciardi
description: Stefano Ricciardi on Software Development
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stefanoric
github_username:  stefanoric

# Site owner
author:
  name                   : "Stefano Ricciardi"
  location               : London, UK
  url                    : "https://stefanoricciardi.com/about/"
  bio                    : "Just another software developer"
  picture                : "/assets/bw_avatar_128x128.jpg"
  twitter                : "stefanoric"
  github                 : "stefanoric"

comments:
  provider: disqus
  disqus:
    shortname: stefanoricciardicom

analytics:
  provider: google
  google:
    tracking_id: "UA-15612899-1"

# seo
google_site_verification: "MHtZpyDb4yWXlvLLGWVYvQrma4L_XLy3kPf1UaIqtrY"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]

permalink: /:year/:month/:day/:title/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      comments: false
      share: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

